# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Build Docker Images and Publish

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.FLOMESH_DOCKERHUB_USERNAME }}
        password: ${{ secrets.FLOMESH_DOCKERHUB_PASSWORD }}

    - name: Build and Push discovery-server
      uses: docker/build-push-action@v2
      with:
        context: ./discovery-server
        platforms: linux/amd64,linux/arm64
        push: true
        tags: flomesh/samples-discovery-server:latest
    
    - name: Build and Push config-service
      uses: docker/build-push-action@v2
      with:
        context: ./config-service
        platforms: linux/amd64,linux/arm64
        push: true
        tags: flomesh/samples-config-service:latest

    - name: Build and Push api-gateway
      uses: docker/build-push-action@v2
      with:
        context: ./api-gateway
        platforms: linux/amd64,linux/arm64
        push: true
        tags: flomesh/samples-api-gateway:latest
        
    - name: Build and Push samples-bookinfo-ratings
      uses: docker/build-push-action@v2
      with:
        context: ./ratings
        platforms: linux/amd64,linux/arm64
        push: true
        tags: flomesh/samples-bookinfo-ratings:latest
        
    - name: Build and Push samples-bookinfo-details
      uses: docker/build-push-action@v2
      with:
        context: ./details
        platforms: linux/amd64,linux/arm64
        push: true
        tags: flomesh/samples-bookinfo-details:latest
        
    - name: Build and Push samples-bookinfo-reviews
      uses: docker/build-push-action@v2
      with:
        context: ./reviews
        platforms: linux/amd64,linux/arm64
        push: true
        tags: flomesh/samples-bookinfo-reviews:latest
        
    - name: Build and Push samples-bookinfo-productpage
      uses: docker/build-push-action@v2
      with:
        context: ./productpage
        platforms: linux/amd64,linux/arm64
        push: true
        tags: flomesh/samples-bookinfo-productpage:latest
